version: 2.1
executors: 
  ios:
    docker:
      - image: alpine
  android:
    docker:
      - image: alpine

jobs:
  buildit:
    parameters:
      platform:
        type: executor
    executor: << parameters.platform >>
    steps:
      - attach_workspace:
            at: /tmp/
      - run: |
          export PLATFORM=`echo $CIRCLE_JOB | sed 's/build-it-//'`
          if [ $PLATFORM = android ]
          then
            mkdir android
            mkdir android/app
            mkdir android/app/build
            mkdir android/app/build/outputs
            mkdir android/app/build/outputs/apk
            echo hello >> android/app/build/outputs/apk/file1
            cat android/app/build/outputs/apk/file1
            mkdir workspace
            mkdir workspace/android
            cp android/app/build/outputs/* workspace/android
          else
            mkdir ios
            echo hello >> ios/main.jsbundle
            cat ios/main.jsbundle
            mkdir workspace
            mkdir workspace/ios
            cp ios/main.jsbundle workspace/ios
          fi
          
      - persist_to_workspace:
            root: workspace
            paths:
              - ./*
          
workflows:
  build:
    jobs:
      - buildit:
          name: build-it-<< matrix.platform >>
          matrix:
            alias: "build-it"
            parameters:
              platform: ["ios", "android"]
            
