version: 2.1

parameters:
  environment:
    type: string
    default: "dev"

jobs:
  trigger:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
          command: |
            curl -X POST \
            --header "Circle-Token: $CIRCLE_TOKEN" \
            --header "Content-Type: application/json" \
            --header 'Accept: application/json' \
            --data '{
              "parameters": {
                "environment": "preprod"
              }
            }' \
            https://circleci.com/api/v2/project/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline
  print:
    docker:
      - image: cimg/base:stable
    resource_class: small
    parameters: 
      message:
        type: string
    steps:
      - run: 
          name: "Print Message"
          command: echo "<< parameters.message >> --- << pipeline.parameters.environment >>"


workflows:
  "Dev Workflow":
    when: 
      equal: [ "dev", << pipeline.parameters.environment >> ]
    jobs:
      # - print:
      #     message: "We here"
      - trigger

  "Preprod Workflow":
    when: 
      equal: [ "preprod", << pipeline.parameters.environment >> ]
    jobs:
      - print:
          message: "We here"
