version: 2.1

parameters:
  environment:
    type: string
    default: "dev"

jobs:
  main:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
          name: "Print Message"
          command: echo "We are here --- << pipeline.parameters.environment >>"

workflows:
  "Some Workflow":
    jobs:
      - main
