version: 2.1

parameters:
  environment:
    type: string
    default: "dev"

jobs:
  trigger:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: |
            curl -u ${CIRCLE_TOKEN}: \
            -d 'build_parameters[environment]=preprod' \
            https://circleci.com/api/v1.1/project/git/dmillikan/circle-lab/tree/master
  print:
    docker:
      - image: cimg/base:stable
    parameters: 
      message:
        type: string
    steps:
      - run: 
          name: "Print Message"
          command: echo "<< parameters.message >> --- << pipeline.parameters.environment >>"


workflows:
  "Dev Workflow":
    when: 
      equal: [ "dev", << pipeline.parameters.environment >> ]
    jobs:
      - print:
          message: "We here"
      - trigger

