version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: |
          mkdir ios
          echo hello >> ios/main.jsbundle
          cat ios/main.jsbundle
      - store_artifacts:
          path: ios
          
          
