version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: |
          mkdir ios
          echo hello >> ios/main.jsbundle
          cat ios/main.jsbundle
          
          # mkdir android
          # mkdir android/app
          # mkdir android/app/build
          # mkdir android/app/build/outputs
          # mkdir android/app/build/outputs/apk
          # echo hello >> android/app/build/outputs/apk/file1
          # cat android/app/build/outputs/apk/file1
      - store_artifacts:
          path: ios
      - store_artifacts:
          path: android/app/build/outputs/apk
          destination: android    
          
