version: 2.1

parameters:
  environment:
    type: string
    default: "dev"

jobs:
  print:
    docker:
      - image: cimg/base:stable
    parameters: 
      message:
        type: string
    steps:
      - run: 
          name: "Print Message"
          command: echo "<< parameters.message >> --- << pipeline.parameters.environment >>"


workflows:
  "Dev Workflow":
    when: 
      equal: [ "dev", << pipeline.parameters.environment >> ]
    jobs:
      - print:
          message: "We in dev"

