version: 2.1

parameters:
  environment:
    type: string
    default: "dev"

jobs:
  main:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Print Message"
          command: echo "We are here --- << pipeline.parameters.environment >>"
      - run:
          name: "Promoting"
          command: ./promote.sh << pipeline.parameters.environment >> gh
workflows:
  "<< pipeline.parameters.environment >> Workflow":
    jobs:
      - main
