version: 2.1

parameters:
  environment:
    type: string
    default: "dev"

jobs:
  main:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Print Message"
          command: echo "We are here --- << pipeline.parameters.environment >>"
      - run:
          name: "Promoting"
          command: ./promote.sh << pipeline.parameters.environment >> gh
workflows:
  Deploy Dev:
    when:
      condition:
        equal: [ "dev" , << pipeline.parameters.environment >> ]
    jobs: &deploy_job
      - main

  Deploy Preprod:
    when:
      condition:
        equal: [ "preprod" , << pipeline.parameters.environment >> ]
    jobs: *deploy_job
  
  Deploy Production:
    when:
      condition:
        equal: [ "preprod" , << pipeline.parameters.environment >> ]
    jobs: *deploy_job