version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: |
          mkdir ios
          echo hello >> ios/main.jsbundle
          cat ios/main.jsbundle
          
          # mkdir android
          # mkdir android/app
          # mkdir android/app/build
          # mkdir android/app/build/outputs
          # mkdir android/app/build/outputs/apk
          # echo hello >> android/app/build/outputs/apk/file1
          # cat android/app/build/outputs/apk/file1
      - persist_to_workspace:
            root: ios
            paths:
                - ios/main.jsbundle
      - persist_to_workspace:
            root: android
            paths:
              - android/app/build/outputs/apk/*
          
          
