version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: |
          mkdir ios
          echo hello >> ios/main.jsbundle
          cat ios/main.jsbundle
          
          mkdir android/app/build/outputs/apk
          echo hello >> android/app/build/outputs/apk/file1
      - store_artifacts:
          path: ios
          
          
