version: 2.1

parameters:
  environment:
    type: string
    default: "dev"

jobs:
  trigger:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: |
            curl --user ${CIRCLE_TOKEN}: \
            --data 'build_parameters[environment]=preprod' \
            https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
  print:
    docker:
      - image: cimg/base:stable
    parameters: 
      message:
        type: string
    steps:
      - run: 
          name: "Print Message"
          command: echo "<< parameters.message >> --- << pipeline.parameters.environment >>"


workflows:
  "Dev Workflow":
    when: 
      equal: [ "dev", << pipeline.parameters.environment >> ]
    jobs:
      - print:
          message: "We here"
      - trigger

  "Preprod Workflow":
    when: 
      equal: [ "preprod", << pipeline.parameters.environment >> ]
    jobs:
      - print:
          message: "We here"
